#python rename_procs.py --inputPath rawRootFiles/2lss/2016/
#python rename_procs.py --inputPath rawRootFiles/2l2tau/2016/
#python rename_procs.py --inputPath rawRootFiles/3l/2016/
#python rename_procs.py --inputPath rawRootFiles/3l1tau/2016/
#python rename_procs.py --inputPath rawRootFiles/1l3tau/2016/
#python rename_procs.py --inputPath rawRootFiles/0l4tau/2016/
#python rename_procs.py --inputPath rawRootFiles/4l/2016/
#python rename_procs.py --inputPath rawRootFiles/2lss/2018/
#python rename_procs.py --inputPath rawRootFiles/2l2tau/2018/
#python rename_procs.py --inputPath rawRootFiles/3l/2018/
#python rename_procs.py --inputPath rawRootFiles/3l1tau/2018/
python rename_procs.py --inputPath rawRootFiles/1l3tau/2018/
python rename_procs.py --inputPath rawRootFiles/0l4tau/2018/
python rename_procs.py --inputPath rawRootFiles/4l/2018/
#python rename_procs.py --inputPath rawRootFiles/2lss/2017/
python rename_procs.py --inputPath rawRootFiles/2l2tau/2017/
#python rename_procs.py --inputPath rawRootFiles/3l/2017/
python rename_procs.py --inputPath rawRootFiles/3l1tau/2017/
python rename_procs.py --inputPath rawRootFiles/1l3tau/2017/
python rename_procs.py --inputPath rawRootFiles/0l4tau/2017/
python rename_procs.py --inputPath rawRootFiles/4l/2017/
#python rename_procs.py --inputPath rawRootFiles/2lss/2017/
python rename_procs.py --inputPath rawRootFiles/2l2tau/Run2/
#python rename_procs.py --inputPath rawRootFiles/3l/Run2/
python rename_procs.py --inputPath rawRootFiles/3l1tau/Run2/
python rename_procs.py --inputPath rawRootFiles/1l3tau/Run2/
python rename_procs.py --inputPath rawRootFiles/0l4tau/Run2/
python rename_procs.py --inputPath rawRootFiles/4l/Run2/

