# WriteDatacards.py  --removeLowYieldShapes --removeLowImpactShapes  --inputShapes rawRootFiles/WZCR/2018/rebinned/newProcName/addSystFakeRates_hh_3l_hh_3l_OS_mT_WZctrl_leptonW_MET.root --channel WZCR  --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "res" --renamedHHInput --shapeSyst  --forceModifyShapes --output_file CRCards/WZCR/2018/datacard_WZCR_2018  --isCR
# rm rawRootFiles/WZCR/2018/rebinned/newProcName/*mod*
# WriteDatacards.py  --removeLowYieldShapes --removeLowImpactShapes  --inputShapes rawRootFiles/WZCR/2017/rebinned/newProcName/addSystFakeRates_hh_3l_hh_3l_OS_mT_WZctrl_leptonW_MET.root --channel WZCR  --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "res" --renamedHHInput --shapeSyst  --forceModifyShapes --output_file CRCards/WZCR/2017/datacard_WZCR_2017  --isCR
# rm rawRootFiles/WZCR/2017/rebinned/newProcName/*mod*
# WriteDatacards.py  --removeLowYieldShapes --removeLowImpactShapes  --inputShapes rawRootFiles/WZCR/2016/rebinned/newProcName/addSystFakeRates_hh_3l_hh_3l_OS_mT_WZctrl_leptonW_MET.root --channel WZCR  --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "res" --renamedHHInput --shapeSyst  --forceModifyShapes --output_file CRCards/WZCR/2016/datacard_WZCR_2016  --isCR
# rm rawRootFiles/WZCR/2016/rebinned/newProcName/*mod*
WriteDatacards.py  --removeLowYieldShapes --removeLowImpactShapes  --inputShapes rawRootFiles/ZZCR/2018/rebinned/newProcName/addSystFakeRates_hh_4l_OS_dihiggsVisMass.root --channel ZZCR --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "res" --renamedHHInput --shapeSyst  --forceModifyShapes --output_file CRCards/ZZCR/2018/datacard_ZZCR_2018  --isCR
rm rawRootFiles/ZZCR/2018/rebinned/newProcName/*mod*
WriteDatacards.py  --removeLowYieldShapes --removeLowImpactShapes  --inputShapes rawRootFiles/ZZCR/2017/rebinned/newProcName/addSystFakeRates_hh_4l_OS_dihiggsVisMass.root --channel ZZCR --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "res" --renamedHHInput --shapeSyst  --forceModifyShapes --output_file CRCards/ZZCR/2017/datacard_ZZCR_2017  --isCR
rm rawRootFiles/ZZCR/2017/rebinned/newProcName/*mod*
WriteDatacards.py  --removeLowYieldShapes --removeLowImpactShapes  --inputShapes rawRootFiles/ZZCR/2016/rebinned/newProcName/addSystFakeRates_hh_4l_OS_dihiggsVisMass.root --channel ZZCR --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "res" --renamedHHInput --shapeSyst  --forceModifyShapes --output_file CRCards/ZZCR/2016/datacard_ZZCR_2016  --isCR
rm rawRootFiles/ZZCR/2016/rebinned/newProcName/*mod*
