# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=4l --era=2016 --inputPath rawRootFiles/4l/2016/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//4l/2016 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=4l --era=2017 --inputPath rawRootFiles/4l/2017/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//4l/2017 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=4l --era=2018 --inputPath rawRootFiles/4l/2018/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//4l/2018 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=3l --era=2016 --inputPath rawRootFiles/3l/2016/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//3l/2016 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=3l --era=2017 --inputPath rawRootFiles/3l/2017/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//3l/2017 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=3l --era=2018 --inputPath rawRootFiles/3l/2018/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//3l/2018 
python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=2lss --era=2016 --inputPath rawRootFiles/2lss/2016/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//2lss/2016 
python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=2lss --era=2017 --inputPath rawRootFiles/2lss/2017/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//2lss/2017 
python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=2lss --era=2018 --inputPath rawRootFiles/2lss/2018/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//2lss/2018 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=3l_1tau --era=2016 --inputPath rawRootFiles/3l1tau/2016/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//3l1tau/2016 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=3l_1tau --era=2017 --inputPath rawRootFiles/3l1tau/2017/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//3l1tau/2017 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=3l_1tau --era=2018 --inputPath rawRootFiles/3l1tau/2018/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//3l1tau/2018 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=1l_3tau --era=2016 --inputPath rawRootFiles/1l3tau/2016/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//1l3tau/2016 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=1l_3tau --era=2017 --inputPath rawRootFiles/1l3tau/2017/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//1l3tau/2017 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=1l_3tau --era=2018 --inputPath rawRootFiles/1l3tau/2018/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//1l3tau/2018 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=2l_2tau --era=2016 --inputPath rawRootFiles/2l2tau/2016/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//2l2tau/2016 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=2l_2tau --era=2017 --inputPath rawRootFiles/2l2tau/2017/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//2l2tau/2017 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=2l_2tau --era=2018 --inputPath rawRootFiles/2l2tau/2018/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//2l2tau/2018 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=0l_4tau --era=2016 --inputPath rawRootFiles/0l4tau/2016/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//0l4tau/2016 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=0l_4tau --era=2017 --inputPath rawRootFiles/0l4tau/2017/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//0l4tau/2017 
# python writenonresCards.py --removeLowYieldShapes --removeLowImpactShapes  --sigtype nonresNLO --channel=0l_4tau --era=2018 --inputPath rawRootFiles/0l4tau/2018/newProcName/rebinned_quantile/ --outPath nonResCards_NLO//0l4tau/2018 
