# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2016/datacard_3l_2016
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2016/datacard_3l_2016_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2016/datacard_3l_2016_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2017/datacard_3l_2017
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2017/datacard_3l_2017_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2017/datacard_3l_2017_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2018/datacard_3l_2018
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2018/datacard_3l_2018_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2018/datacard_3l_2018_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2016/datacard_4l_2016
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2016/datacard_4l_2016_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2016/datacard_4l_2016_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2017/datacard_4l_2017
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2017/datacard_4l_2017_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2017/datacard_4l_2017_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2018/datacard_4l_2018
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2018/datacard_4l_2018_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2018/datacard_4l_2018_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2016/datacard_3l_1tau_2016
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2016/datacard_3l_1tau_2016_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2016/datacard_3l_1tau_2016_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2017/datacard_3l_1tau_2017
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2017/datacard_3l_1tau_2017_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2017/datacard_3l_1tau_2017_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2018/datacard_3l_1tau_2018
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2018/datacard_3l_1tau_2018_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2018/datacard_3l_1tau_2018_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2016/datacard_1l_3tau_2016
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2016/datacard_1l_3tau_2016_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2016/datacard_1l_3tau_2016_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2017/datacard_1l_3tau_2017
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2017/datacard_1l_3tau_2017_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2017/datacard_1l_3tau_2017_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2018/datacard_1l_3tau_2018
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2018/datacard_1l_3tau_2018_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2018/datacard_1l_3tau_2018_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2016/datacard_0l_4tau_2016
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2016/datacard_0l_4tau_2016_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2016/datacard_0l_4tau_2016_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2017/datacard_0l_4tau_2017
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2017/datacard_0l_4tau_2017_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2017/datacard_0l_4tau_2017_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2018/datacard_0l_4tau_2018
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2018/datacard_0l_4tau_2018_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2018/datacard_0l_4tau_2018_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2016/datacard_2l_2tau_2016
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2016/datacard_2l_2tau_2016_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2016/datacard_2l_2tau_2016_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2017/datacard_2l_2tau_2017
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2017/datacard_2l_2tau_2017_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2017/datacard_2l_2tau_2017_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2018/datacard_2l_2tau_2018
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2018/datacard_2l_2tau_2018_alt1
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2018/datacard_2l_2tau_2018_alt2
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2016/datacard_3l_2016_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2016/datacard_2l_2tau_2016_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2016/datacard_4l_2016_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2016/datacard_3l_1tau_2016_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2016/datacard_1l_3tau_2016_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2016/datacard_0l_4tau_2016_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2017/datacard_3l_2017_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2017/datacard_2l_2tau_2017_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2017/datacard_4l_2017_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2017/datacard_3l_1tau_2017_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2017/datacard_1l_3tau_2017_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2017/datacard_0l_4tau_2017_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2018/datacard_3l_2018_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2018/datacard_2l_2tau_2018_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2018/datacard_4l_2018_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2018/datacard_3l_1tau_2018_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2018/datacard_1l_3tau_2018_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2018/datacard_0l_4tau_2018_alt3
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2016/datacard_3l_2016_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2016/datacard_2l_2tau_2016_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2016/datacard_4l_2016_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2016/datacard_3l_1tau_2016_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2016/datacard_1l_3tau_2016_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2016/datacard_0l_4tau_2016_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2017/datacard_3l_2017_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2017/datacard_2l_2tau_2017_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2017/datacard_4l_2017_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2017/datacard_3l_1tau_2017_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2017/datacard_1l_3tau_2017_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2017/datacard_0l_4tau_2017_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2018/datacard_3l_2018_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2018/datacard_2l_2tau_2018_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2018/datacard_4l_2018_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2018/datacard_3l_1tau_2018_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2018/datacard_1l_3tau_2018_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2018/datacard_0l_4tau_2018_alt4
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2016/datacard_3l_2016_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2016/datacard_2l_2tau_2016_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2016/datacard_4l_2016_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2016/datacard_3l_1tau_2016_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2016/datacard_1l_3tau_2016_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2016/datacard_0l_4tau_2016_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2017/datacard_3l_2017_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2017/datacard_2l_2tau_2017_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2017/datacard_4l_2017_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2017/datacard_3l_1tau_2017_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2017/datacard_1l_3tau_2017_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2017/datacard_0l_4tau_2017_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2018/datacard_3l_2018_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2018/datacard_2l_2tau_2018_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2018/datacard_4l_2018_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2018/datacard_3l_1tau_2018_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2018/datacard_1l_3tau_2018_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2018/datacard_0l_4tau_2018_alt5
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2016/datacard_3l_2016_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2016/datacard_2l_2tau_2016_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2016/datacard_4l_2016_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2016/datacard_3l_1tau_2016_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2016/datacard_1l_3tau_2016_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2016/datacard_0l_4tau_2016_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2017/datacard_3l_2017_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2017/datacard_2l_2tau_2017_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2017/datacard_4l_2017_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2017/datacard_3l_1tau_2017_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2017/datacard_1l_3tau_2017_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2017/datacard_0l_4tau_2017_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_hh_3l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l/2018/datacard_3l_2018_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2l_2tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2l2tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2l_2tau_hh_2l_2tau__sumOS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2l2tau/2018/datacard_2l_2tau_2018_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 4l --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/4l/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_4l_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/4l/2018/datacard_4l_2018_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 3l_1tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/3l1tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_3l_1tau_hh_3l_1tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/3l1tau/2018/datacard_3l_1tau_2018_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 1l_3tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/1l3tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_1l_3tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/1l3tau/2018/datacard_1l_3tau_2018_all
# WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 0l_4tau --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/0l4tau/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_0l_4tau_OS_MVAOutput_C2forSM.root --output_file nonResCards_C2/0l4tau/2018/datacard_0l_4tau_2018_all
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2016/datacard_2lss_2016_all
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2017/datacard_2lss_2017_all
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_all" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2018/datacard_2lss_2018_all
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2016/datacard_2lss_2016
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2017/datacard_2lss_2017
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2018/datacard_2lss_2018
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2016/datacard_2lss_2016_alt1
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2017/datacard_2lss_2017_alt1
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt1" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2018/datacard_2lss_2018_alt1
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2016/datacard_2lss_2016_alt2
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2017/datacard_2lss_2017_alt2
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt2" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2018/datacard_2lss_2018_alt2
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2016/datacard_2lss_2016_alt3
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2017/datacard_2lss_2017_alt3
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt3" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2018/datacard_2lss_2018_alt3
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2016/datacard_2lss_2016_alt4
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2017/datacard_2lss_2017_alt4
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt4" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2018/datacard_2lss_2018_alt4
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2016 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2016/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2016/datacard_2lss_2016_alt5
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2017 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2017/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2017/datacard_2lss_2017_alt5
WriteDatacards.py --removeLowYieldShapes --removeLowImpactShapes --channel 2lss --HHtype "multilepton" --analysis HH --noX_prefix --era 2018 --signal_type "forC2_alt5" --renamedHHInput --shapeSyst  --forceModifyShapes --inputShapes rawRootFiles/2lss/2018/newProcName/rebinned_quantile/addSystFakeRates_hh_2lss_leq1tau_hh_2lss_leq1tau_SS_MVAOutput_C2forSM.root --output_file nonResCards_C2/2lss/2018/datacard_2lss_2018_alt5
rm rawRootFiles/*/*/newProcName/rebinned_quantile/*mod*
