# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=4l --era=2016 --spinCase=spin0 --inputPath rawRootFiles/4l/2016/newProcName/rebinned_quantile/ --outPath resCards_spin0/4l/2016
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=4l --era=2017 --spinCase=spin0 --inputPath rawRootFiles/4l/2017/newProcName/rebinned_quantile/ --outPath resCards_spin0/4l/2017
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=4l --era=2018 --spinCase=spin0 --inputPath rawRootFiles/4l/2018/newProcName/rebinned_quantile/ --outPath resCards_spin0/4l/2018
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=3l --era=2016 --spinCase=spin0 --inputPath rawRootFiles/3l/2016/newProcName/rebinned_quantile/ --outPath resCards_spin0/3l/2016
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=3l --era=2017 --spinCase=spin0 --inputPath rawRootFiles/3l/2017/newProcName/rebinned_quantile/ --outPath resCards_spin0/3l/2017
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=3l --era=2018 --spinCase=spin0 --inputPath rawRootFiles/3l/2018/newProcName/rebinned_quantile/ --outPath resCards_spin0/3l/2018
python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=2lss --era=2016 --spinCase=spin0 --inputPath rawRootFiles/2lss/2016/newProcName/rebinned_quantile/ --outPath resCards_spin0/2lss/2016
python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=2lss --era=2017 --spinCase=spin0 --inputPath rawRootFiles/2lss/2017/newProcName/rebinned_quantile/ --outPath resCards_spin0/2lss/2017
python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=2lss --era=2018 --spinCase=spin0 --inputPath rawRootFiles/2lss/2018/newProcName/rebinned_quantile/ --outPath resCards_spin0/2lss/2018
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=3l_1tau --era=2016 --spinCase=spin0 --inputPath rawRootFiles/3l1tau/2016/newProcName/rebinned_quantile/ --outPath resCards_spin0/3l1tau/2016
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=3l_1tau --era=2017 --spinCase=spin0 --inputPath rawRootFiles/3l1tau/2017/newProcName/rebinned_quantile/ --outPath resCards_spin0/3l1tau/2017
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=3l_1tau --era=2018 --spinCase=spin0 --inputPath rawRootFiles/3l1tau/2018/newProcName/rebinned_quantile/ --outPath resCards_spin0/3l1tau/2018
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=1l_3tau --era=2016 --spinCase=spin0 --inputPath rawRootFiles/1l3tau/2016/newProcName/rebinned_quantile/ --outPath resCards_spin0/1l3tau/2016
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=1l_3tau --era=2017 --spinCase=spin0 --inputPath rawRootFiles/1l3tau/2017/newProcName/rebinned_quantile/ --outPath resCards_spin0/1l3tau/2017
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=1l_3tau --era=2018 --spinCase=spin0 --inputPath rawRootFiles/1l3tau/2018/newProcName/rebinned_quantile/ --outPath resCards_spin0/1l3tau/2018
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=2l_2tau --era=2016 --spinCase=spin0 --inputPath rawRootFiles/2l2tau/2016/newProcName/rebinned_quantile/ --outPath resCards_spin0/2l2tau/2016
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=2l_2tau --era=2017 --spinCase=spin0 --inputPath rawRootFiles/2l2tau/2017/newProcName/rebinned_quantile/ --outPath resCards_spin0/2l2tau/2017
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=2l_2tau --era=2018 --spinCase=spin0 --inputPath rawRootFiles/2l2tau/2018/newProcName/rebinned_quantile/ --outPath resCards_spin0/2l2tau/2018
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=0l_4tau --era=2016 --spinCase=spin0 --inputPath rawRootFiles/0l4tau/2016/newProcName/rebinned_quantile/ --outPath resCards_spin0/0l4tau/2016
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=0l_4tau --era=2017 --spinCase=spin0 --inputPath rawRootFiles/0l4tau/2017/newProcName/rebinned_quantile/ --outPath resCards_spin0/0l4tau/2017
# python writeResCards.py --removeLowYieldShapes --removeLowImpactShapes  --channel=0l_4tau --era=2018 --spinCase=spin0 --inputPath rawRootFiles/0l4tau/2018/newProcName/rebinned_quantile/ --outPath resCards_spin0/0l4tau/2018
